<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>10</LangVersion>
    <NuGetAudit>false</NuGetAudit>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="obj/**/*.cs;bin/**/*.cs" />
    <Compile Include="../HapticEngine.cs" Link="HapticEngine.cs" />
    <Compile Include="../HapticOutput.cs" Link="HapticOutput.cs" />
  </ItemGroup>
</Project>
